licenses(["notice"])  # Apache 2.0

sh_binary(
    name = "build_pip_package",
    srcs = ["build_pip_package.sh"],
    data = [
        "//tensorflow_metadata/proto/v0:metadata_v0_proto_py_pb2",
    ],
)
