licenses(["notice"])  # Apache 2.0

sh_binary(
    name = "move_generated_files",
    srcs = ["move_generated_files.sh"],
    data = [
        "//tensorflow_metadata/proto/v0:metadata_v0_proto_py_pb2",
    ],
)
